### PR TITLE
Lock rack version to 1.x [#126262085]

### PR DESCRIPTION
**Pull request by nc-desain**
Prevent version incompatibility issues

### CODE REVIEW

**Comment by pittmanw** [comment]
If we want the lac gem to use this, we'll need to build a new gem version after this is merged. Please add the lac gem tracker id to the title before merging.

:shipit:

**Comment by nc-desain** [comment]
Should I add a commit to bump the version number?

**Comment by pittmanw** [comment]
Yes, and we use [semver](http://semver.org/) conventions for our version numbers.

**Comment by nc-desain** [comment]
Added the version commit. Is there a release command to put this version on the gem server?

**Pull request merged**
